version: "3.8"

services:
  redis:
    image: "redis:latest"
    container_name: "redis-server"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  app:
    build: .
    container_name: "python-app"
    command: ["python", "app.py"]  # Replace with the command to run your app
    volumes:
      - .:/app  # Mount the app directory inside the container
    ports:
      - "8000:8000"  # Example port for your FastAPI app
    depends_on:
      - redis  # Ensure Redis is started before the app
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  test:
    build: .
    container_name: "python-app-tests"
    command: ["pytest", "--maxfail=1", "--disable-warnings", "-q"]
    volumes:
      - .:/app  # Mount the app directory inside the container
    depends_on:
      - redis  # Ensure Redis is started before the tests
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
